cache-file: $cache
overlay-mode: true
fast-comparison: true
use-local-cache: true
threads: 4
file-filter: 

variables:
  cache: .cache.json
  cos-cli: coscli-windows.exe
  bucket: 'cos://sdfs-1254063044'

commands:
  _workdir: 
  _encoding: utf-8
  download-cache: $cos-cli cp $bucket/$cache $cache
  upload-cache: $cos-cli cp "$apath" $bucket/$cache
  delete-file: $cos-cli rm "$bucket/$rpath" --force
  delete-dir: $cos-cli rm "$bucket/$rpath/" --force
  upload-file: $cos-cli sync "$apath" "$bucket/$rpath"
  upload-dir: $cos-cli cp empty.txt "$bucket/$rpath/"