state-file: $state
overlay-mode: true
fast-comparison: true
use-local-state: false
threads: 4
file-filter: 

variables:
  state: .state.json
  cli: ossutil64.exe
  bucket: 'oss://sdfdsfewffwefwefwefwef'

commands:
  _workdir: 
  _encoding: utf-8
  download-state: $cli cp $bucket/$state $state --force
  upload-state: $cli cp "$apath" $bucket/$state --force
  delete-file: $cli rm "$bucket/$rpath" --force
  delete-dir: 
  upload-file: $cli cp "$apath" "$bucket/$rpath" --force
  make-dir: 